#ifndef GLOBALCONST_H
#define GLOBALCONST_H

#define PLAYER_HIGHT 32
#define PLAYER_WIDTH 32
#define PLAYER_MOVE_SPEED 8
#define MAX_PLAYERS 4

#define WINDOW_WIDTH 1024
#define WINDOW_HEIGHT 1024

#define NUM_SUBTEXTURES 4
#define TEXTURE_WIDTH 128
#define TEXTURE_HEIGHT 128
#define SUBTEXTURE_WIDTH 32
#define SUBTEXTURE_HEIGHT 32

#define SERVER_IP "127.0.0.1"
#define SERVER_PORT 12345

#define MAX_COINS 300
#define COINS_MAX_W 12
#define COINS_MAX_H 12
#define COIN_FRAMES 8
#define COIN_ANIMATION_DELAY 15
#endif